name: Build Xamarin.IOS app (mac)

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    
    - uses: actions/checkout@v3
    
    #- name: Setup .NET Core SDK 5.0.x
    #  uses: actions/setup-dotnet@v3
    #  with:
    #    dotnet-version: '5.0.x'
    #
    #- name: Set default Xamarin SDK versions
    #  run: |
    #    $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=14.10


    - name: Install dependencies
      run: nuget restore MyCoffeeApp.sln

    - name: Build
      run: msbuild ./MyCoffeeApp/MyCoffeeApp.iOS/MyCoffeeApp.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild
