name: Build Xamarin.Android app (win)

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:    
    - uses: actions/checkout@v3    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Install dependencies
      run: nuget restore MyCoffeeApp.sln
    - name: Build
      run: |
        msbuild .\MyCoffeeApp\MyCoffeeApp.Android\MyCoffeeApp.Android.csproj /t:PackageForAndroid /p:Configuration=Debug
                     
